### ISSUE TITLE
How to get Layout_Hack accepted by linux builds

### ISSUE THREAD

**Issue by rgleason** [rgleason/LogbookKonni_pi#12]
How to Gett Layout_Hack   accepted by Linux.  It is causing many Linux failures.

https://app.circleci.com/pipelines/github/rgleason/LogbookKonni_pi/40/workflows/fb954f4f-c489-4bac-87a8-43afff9e8e72/jobs/377

https://github.com/rgleason/LogbookKonni_pi/tree/master-updateFE

**Comment by rgleason** [comment]
-- CMakeLists: Adding target link libraries to logbookkonni_pi
-- CMakeLists_TINYXML: Building TinyXML
CMake Error at CMakeLists.txt:293 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".


-- Configuring incomplete, errors occurred!

**Comment by filochard** [comment]
https://github.com/rgleason/LogbookKonni_pi/issues/6#issuecomment-829266606

he proposed to revert this line from add_compile_definitions("LAYOUTS_HACK") to ancient add_definitions("-DLAYOUTS_HACK")

**Comment by rgleason** [comment]
Fixed not and building, but not being deployed..
