### ISSUE TITLE
segfault with logbookkonni installed as a rpm

### ISSUE THREAD

**Issue by filochard** [rgleason/LogbookKonni_pi#32]
Hi Rick

I am building updated rpms of logbookkonni_pi for Mageia
And I get something I can't understand
On my computer I already have a user owned directory (/home/myusername/.opencn/ ) 
besides the installation directories (inside /usr/lib64/ and /usr/share/opencpn/)

If I use this existing configuration directory I have no problem after having updated logbookkonni (the only changes are done in the system directories )

But if I try a kind of "fresh first launch" of opencpn 
(renaming /home/myusername/.opencn/ to /home/myusername/.opencnbak/)
I fall in a problem I don't understand at all

1) first I activate all the plugins (except logbook) and everything is OK
2) Then I activate the logbook plugin and install the Layouts.zip it's OK too (the layouts are unzipped and  copied in my user directory in the right place) 
3) I close the settings windows (apply button, OK button) the logbook icon appears in the icons tray
But after that
4)  when I click on the logbook icon I get immediately a Segfault

I did try to build several versions of logbookkonni (from a gitclone your code, from the one of delatlabel or from the one from ptpulp... even tried to build from older tagged verrsions)
I always get a segfault with the new created /home/myusername/.opencn directory  but never when reusing my backupped directory after having erased the new created one

There's perhaps something wrong with the new created icon button of logbookkoni in a freshly created directory (perhaps the source code doesn't like gtk3 ?)

Here is a debug file , hoping it will help
[gdb.bt.txt](https://github.com/rgleason/LogbookKonni_pi/files/6734588/gdb.bt.txt)

**Comment by filochard** [comment]
Hi again
The more I think about this the more I wonder if the problem doesn't come from the opencpn.conf, in the part of it which is created when activating the logbook  :  that's where may appears the only difference

For each test I used the same version of logbookkonni and compared what happens with a freshly created /.opencpn/directory and when using my previous working one

**Comment by rgleason** [comment]
I have read the attached file, but I am not the one who would understand it.  It sounds to me like the icon load procedure may have a wrong path.   I will try to find that section.

**Comment by rgleason** [comment]
@filochard 

It appears that I lost track of this plugin and did not update it.  Version 1.4.14.0 in PIM is superceded by several PR and they have not been added to PIM.

In updating this plugin to  fe2 v1.0.172 I cleaned out all references to logbook, including data directories.
I then tried installing a fresh new version locally created with the 172 update.  The layouts.zip landed in windows
%localappdata%\opencpn\plugins\logbookkonni_pi\data\  or   "C:\Users\Rick\AppData\Local\opencpn\plugins\logbookkonni_pi\data"   which also contained the svg icons, and help.html

I navigated to this location and extracted in place to create the layout files.
Then I tried to do this from within "preferences"  using the "Install" button, picking the layouts.zip and this is the screenshot after doing that.

![Screenshot (245)](https://user-images.githubusercontent.com/2363959/123961664-9abb3980-d97e-11eb-8a82-46bca4437921.png)

Where it appears that the layout files are being installed to  "Programdata/openpcn/plugins/logbook/data"
When I check this directory, I find that the layout files have indeed been extracted to that location.
So this has to be changed.

Also I find that the saved user *.txt files are being saved to that location rather than to %localappdata%\opencpn\plugins\logbookkonni_pi\data\    
This also has to be changed because it will not work in flatpak.

**Comment by ptulp** [comment]
There is no GetpPrivateApplicationLocation function defined, there is a GetpPrivateApplicationDataLocation function but that points to a opencpn/plugins/logbook location.
There was never a opencpn/plugins/logbookkonni_pi/data location in the logbook plugin.
Who decided that the files should be there?

**Comment by rgleason** [comment]
Peter, that is correct, I wrote the wrong name for the function.
Flatpak is a special case where user written data has to go into a special directory, that allows the user to write the data.
The icons system can continue using that directory, but any user writable data has to go in the special directory.
On a Windows OS for logbookkonni_pi  the directory that is writable is  %localappdata%/opencpn/plugins/logbookkonni_pi/data/   and the text files for logbook should all be located there along with all the layout files.

Some of the basic functions are using wrong directories so flatpak gets the segfault.

I have a version just coming out, that may help (Mike made some good changes to paths) , but it will need some improvements I think.

**Comment by rgleason** [comment]
@filochard  
Please back up your logbook data to some remote place.
Please remove all logbook  dlls,  logbookkonni_pi/data  in  the cache, and various directories. 
Try to install the PIM     Logbookkonni v1.4.14.9 + fix icons + try android fix
and notice where the files are installed, and what is installed.
Then try to install  Layouts.zip from the Preferences and advise where that is going and lands.

I think we need to make some more changes to the paths in the plugin.

**Comment by rgleason** [comment]
1.   Windows - layouts.zip lands %localappdata%\opencpn\plugins\logbookkonni_pi\data\ or "C:\Users\Rick\AppData\Local\opencpn\plugins\logbookkonni_pi\data" which also contained the svg icons, and help.html.   This is the correct action.

2.  Copy  .svg icons from   "%localappdata%\opencpn\plugins\logbookkonni_pi\data\ " using  getpPrivateApplicationDataLocation  to  
"programdata/opencpn/plugins/logbook/data/"  using GetPluginDataDir("logbookkonni_pi"
The icons are typically accessed from there.

3. Additionally the plugin should be extracting layouts.zip to  "%localappdata%\opencpn\plugins\logbookkonni_pi\data\ " using  getpPrivateApplicationDataLocation  where the user can write data in flatpak, rather than where it is going now  "programdata/opencpn/plugins/logbook/data/".

4. I think the final change needed is to save and load the logbook data to and from "%localappdata%\opencpn\plugins\logbookkonni_pi\data\ " using  getpPrivateApplicationDataLocation  where the user can write data in flatpak, rather than where it is going now  "programdata/opencpn/plugins/logbook/data/" .

**Comment by rgleason** [comment]
**logbook_pi.cpp line 993**
saveconfig  

**logbook_pi.cpp  line 1490**
loadlayouts   of  "LogbookKonni*.zip"  using  StandardPath()
This file is then extracted to some location  which needs to be changed.

The next thing to do is to copy the svg icons as part of the initialization of the plugin so they are available where needed

**Comment by rgleason** [comment]
Test of Logbook 1.4.14.9
Initial installation:
%localappdata%/opencpn/plugins/logbookkonni_pi/data/
   Images
   OLD
   Help.html
   Layouts.zip
   LogbookKonni_pi.svg
   LogbookKonni_pi_rollover.svg
   LogbookKonni__pi_toggled.svg

NOTE: The svg icons are working properly out  of the box. There is no need to copy them on initialization as stated earler!

C:\ProgramData\opencpn\plugins\logbook\data
  boat.txt
 buyparts.txt
 crewlist.txt
equipment.txt
logbook.txt
repairs.txt
service.txt
Textblocks.txt
watchlist.txt

What is needed is for these txt files to be written and read out of 
%localappdata%/opencpn/plugins/logbookkonni_pi/data/    instead.

Also to expand layoutszip in place to that directory as well.

**Comment by filochard** [comment]
Hi Rick
1) The first thing I have to clarify is that I created this new issue  about building a rpm with the code of logbookkonni whatever the source code I use : Delatlabel, Ptpulp or yours...
When I install this rpm, and activate it it induces a segfault of opencpn when I try to launch the plugin by clicking its icon
This bug concerns only linux distributions with opencpn installed by a package built for this distribution and plugins packages installed one by one (not using the plugin manager)
This doesn't concern Flatpak nor Windows
I will add an other comment specially for this, just after this one

2) About flatpak
Before trying this
> @filochard
> Please back up your logbook data to some remote place.
> Please remove all logbook dlls, logbookkonni_pi/data in the cache, and various directories.
> Try to install the PIM Logbookkonni v1.4.14.9 + fix icons + try android fix
> and notice where the files are installed, and what is installed.
> Then try to install Layouts.zip from the Preferences and advise where that is going and lands.
> 
I wrote to you in an other issue that version 1.4.14.3 worked perfectly for flatpak
https://github.com/rgleason/LogbookKonni_pi/issues/26#issuecomment-862467460
Everything needed is in the right place
User's files are copied or written in the right place
![app-data](https://user-images.githubusercontent.com/16304019/124183819-0c979e00-dab9-11eb-8ab2-e3bfe24f8321.png)
![userowned-data](https://user-images.githubusercontent.com/16304019/124183825-102b2500-dab9-11eb-9d72-ac123fc90cb2.png)
[logbook.version.txt](https://github.com/rgleason/LogbookKonni_pi/files/6750541/logbook.version.txt)
[logbook.dirs.txt](https://github.com/rgleason/LogbookKonni_pi/files/6750542/logbook.dirs.txt)
[logbook.files.txt](https://github.com/rgleason/LogbookKonni_pi/files/6750543/logbook.files.txt)

Nevertheless I will try version 1.4.14.9 in flatpak

**Comment by filochard** [comment]
talking about what I opened this issue about 
> Hi again
> The more I think about this the more I wonder if the problem doesn't come from the opencpn.conf, in the part of it which is created when activating the logbook : that's where may appears the only difference

The more I compare the part of opencpn.conf concerning logbook the more I think that the source doesn't like to be built with the last version of wxgtk (3.1 in Mageia8)
As I told you in the beginning of this issue, if I update the rpms of opencpn and its plugins this doesn't modify the user's specific config directory :  /home/myusername/.opencpn and everything works well

But if I bakup this directory  (renaming it /home/myusername/.opencpnbak) ... and launch again opencpn it's like a first use of it : it creates a new /home/myusername/.opencpn directory
> 
> For each test I used the same version of logbookkonni and compared what happens with a freshly created 
/.opencpn/ directory and when using my previous working one

I found where the problem is : you need just to look at the end of the three extracts of opencpn.conf
-  the first is from flatpak (built with 18.08 and an old version of wxgtk )  it works perfectly no segfault
-  the second is from a previous installation of opencpn and its plugins (before they were updated and built with the last wxgtk3.1) it works too because it has not been modified when simply updating the libraries in the system
- the third was created by a "first launch" of opencpn 
[logbook-config-flatpak.txt](https://github.com/rgleason/LogbookKonni_pi/files/6750725/logbook-config-flatpak.txt)
[logbook-config-oldrpm.txt](https://github.com/rgleason/LogbookKonni_pi/files/6750727/logbook-config-oldrpm.txt)
[logbook-config-newrpm.txt](https://github.com/rgleason/LogbookKonni_pi/files/6750730/logbook-config-newrpm.txt)
As you can see there's quite no difference between the conf of flatpak and the one created by the old rpms (built with an olderversion of wxgt)
NavGridColWidth=144,89,63,35,157,58,86,143,54,50,55,57,62,248
WeatherGridColWidth=69,78,74,66,81,76,81,76,63,76,92,89,80,80,80
MotorGridColWidth=62,96,63,0,0,0,82,75,63,66,0,0,116,76,97,75,77,62,80,124,80,250,0,0
CrewGridColWidth=60,154,139,140,50,78,127,116,118,147,110,82,155,261,243
WakeGridColWidth=97
EquipGridColWidth=120,296,151,297
OverviewGridColWidth=153,144,60,60,100,73,93,96,70,80,80,80,80,114,108,93,129,80,80,100,80,80,80,80,123,80,80,80,80,80,80,110,0
ServiceGridColWidth=50,400,100,100,80,80,80
RepairsGridColWidth=50,400
BuyPartsGridColWidth=50,101,400,325,74,255


But in the conf created by logbookkonni built with wxgtk3.1 the Grid part is empty

NavGridColWidth=
WeatherGridColWidth=
MotorGridColWidth=
CrewGridColWidth=
WakeGridColWidth=
EquipGridColWidth=
OverviewGridColWidth=
ServiceGridColWidth=
RepairsGridColWidth=
BuyPartsGridColWidth=

It should have been created when launching logbook from its icon

NB beside this error in opencpn.conf all the files are in their right place (txt Layouts OK)

**Comment by filochard** [comment]
In the code
LogbookKonni_pi/cmake/FindGTK3.cmake

this line : 
pkg_check_modules(GTK3 gtk+-3.0)
seems to exclude the 3.1 version ?

Elsewhere (in  LogbookKonni_pi/cmake/PluginSetup.cmake  I saw that the dependancies are
 set(PACKAGE_DEPS "libc6, libwxgtk3.0-0, wx3.0-i18n, libglu1-mesa (>= 7.0.0), libgl1-mesa-glx (>= 7.0.0), zlib1g, bzip2, libportaudio2")

Is this the reason why logbookkonni.so is unable to create the user's owned wxwidgets and grid characteristics with the last version of wxgtk 3.1 when it could with wxgtk3.0

Is there a compatibility problem when opencpn itself is built with wxgtk3.1 and logbookkonni with wxgtk3.0 ?

NB the gdb.bt.txt file that looks for the causes of the segfault refers to wxwidgets created by logbookkoni

**Comment by rgleason** [comment]
This line is part of testplugin frontend2 (cmake)  and is a similar problem to what we have been having with OS version numbers.  Perhaps Jon G will have some ideas.
  
```
LogbookKonni_pi/cmake/FindGTK3.cmake

this line :
pkg_check_modules(GTK3 gtk+-3.0)
seems to exclude the 3.1 version ?
```

**Comment by filochard** [comment]
That makes me think that we had to patch the CMakeLists.txt of opencpn 5.2.4 to build it with wxgtk3.1

[opencpn-5.0.2-mga-cmakelists.txt_wxgtk_version.patch.txt](https://github.com/rgleason/LogbookKonni_pi/files/6751126/opencpn-5.0.2-mga-cmakelists.txt_wxgtk_version.patch.txt)
[opencpn-5.2.4-mga-cmakelists.txt_wxgtk_test.patch.txt](https://github.com/rgleason/LogbookKonni_pi/files/6751127/opencpn-5.2.4-mga-cmakelists.txt_wxgtk_test.patch.txt)

**Comment by filochard** [comment]
I will try to patch the logbookkonni FindGTK3.cmake 
But not tonight..

**Comment by jongough** [comment]
Currently  OCPN only supports wxWidgets 3.0* and GTK3. Until that changes none of the plugins can support newer versions. See the equivalent file in OCPN.

**Comment by filochard** [comment]
> Currently OCPN only supports wxWidgets 3.0* and GTK3. Until that changes none of the plugins can support newer versions. See the equivalent file in OCPN.

Indeed ? we could build opencpn with gtk3.1 and wxgtku3.1
Look at
https://github.com/OpenCPN/OpenCPN/issues/2075
from
https://github.com/OpenCPN/OpenCPN/issues/2075#issue-730971323
to 
https://github.com/OpenCPN/OpenCPN/issues/2075#issuecomment-718123902

And we could build most of its plugins with gtk3.1 and wxgtku3.1 they work.
The only plugin that fails to build  is logbookkonni...

**Comment by filochard** [comment]
> I will try to patch the logbookkonni FindGTK3.cmake
> But not tonight..

I applied a patch so that wxgtk3.1 is really used to build the rpm (instead of gtk3.0 which was used even if gtk3.1 was present)

Segfault...

And in the part of opencpn.conf created by logbookkonni really built with wxgtk3.1 the Grid part is empty

NavGridColWidth=
WeatherGridColWidth=
MotorGridColWidth=
CrewGridColWidth=
WakeGridColWidth=
EquipGridColWidth=
OverviewGridColWidth=
ServiceGridColWidth=
RepairsGridColWidth=
BuyPartsGridColWidth=

**Comment by jongough** [comment]
The programs will build, but if OCPN is built for wxWidgets 3.0* and GTK3 it doesn't help. If OCPN is built for the newer versions then it will load plugins built that way. I am just maintaining compatibility with OCPN in the auto builds. If you want to do your own builds there is nothing that should stop you doing so. I just have to be careful that I don't let fontend2 get ahead of OCPN, hence my statement.

**Comment by filochard** [comment]
Thanks
You gave me something to dig : 
I will rebuild all the staff (opencpn and plugins) with wxgtk 3.0 instead of wxgtk 3.1 and test them...
This is perhaps the reason why logbookkonni segfault ....

**Comment by filochard** [comment]
Sorry for the noise !!!
Indeed I had stupidly rebuild all our opencpn packages with our updated wxgtk 3.1 thinking that they might be updated too !!!

 Indeed they absolutely must be built with wxgtk 3.0 
I rebuild rpms for opencpn and logbookkonni upon wxgtk 3.0 
No more segfault    ;-)

You may close this stupid and useless issue

**Comment by rgleason** [comment]
filochard    That's good, but I still want to understand what is happening now with logbook, in flatpak and ubuntu. etc.  so lets continue this separate matter  here https://github.com/rgleason/LogbookKonni_pi/issues/26#issuecomment-862467460.  

You can close this yourself to as you opened it!
