### ISSUE TITLE
Useless icons in src/ directory

### ISSUE THREAD

**Issue by leamas** [rgleason/LogbookKonni_pi#35]
The src/ directory contains some .svg and .png icons which are unusable. The reason is that files in the src/ directory are not installed. This means that they don't go into the tarball and thus are unavailable in runtime.

Note that this is *not* about the .xpm files. These are true sources which are compiled into the program.

Possible fixes includes to just remove these files or move them to data/. Files in data/ are installed and becomes available in runtime.

**Comment by rgleason** [comment]
I do not know what those icons are used for yet and am reluctant to simply delete them.
Could they likely be part of the help system?

**Comment by leamas** [comment]
Why reluctant? This is git, everything is available even after removing it. I would just remove them, for sure (after testing, of course).

**Comment by rgleason** [comment]
ok will do.

**Comment by rgleason** [comment]
Alec, all builds have failed.
So #if issue.
https://github.com/rgleason/LogbookKonni_pi

**Comment by leamas** [comment]
link to build logs?

**Comment by leamas** [comment]
hm.... some kind of typo after I did my builds? This patch seems to fix things:

```
diff --git a/src/Logbook.cpp b/src/Logbook.cpp
index 32c59b1..411c9d6 100644
--- a/src/Logbook.cpp
+++ b/src/Logbook.cpp
@@ -17,7 +17,7 @@
  * along with this program.  If not, see <http://www.gnu.org/licenses/>.^M
 */^M
 
-+#ifndef WX_PRECOMP
+#ifndef WX_PRECOMP
 #include <wx/wx.h>
 #endif
```

**Comment by rgleason** [comment]
Thanks, I must be sun crazed. I was trying to find the error on my local master.

**Comment by rgleason** [comment]
That fixed 90% of the builds.  Now just have the three flatpak failing.
Thanks for adding 20.08.

I am not able to find the source of the 3 flatpak errors, but these should help.

**circleci-build-flatpak.sh**

Fatal: ambiguous argument 'sd': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Failed to download sources: module Logbook: Child process exited with code 128
bash: app/files/metadata.xml: No such file or directory
-- Stripping app/files/lib/opencpn/libLogbookKonni_pi.so
strip: 'app/files/lib/opencpn/libLogbookKonni_pi.so': No such file
-- Building Logbook-1.4.15.2-+943.f7f99a8_flatpak-18.08-x86_64.tar.gz
/home/circleci/project/build/Logbook-1.4.15.2-+943.f7f99a8_flatpak-18.08-x86_64.tar.gz: No such file or directory
CMake Error at checksum.cmake:7 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


```
-- Computing checksum in Logbook-1.4-flatpak-18.08.xml
make[3]: Leaving directory '/home/circleci/project/build'
Built target flatpak
make[2]: Leaving directory '/home/circleci/project/build'
/usr/bin/cmake -E cmake_progress_start /home/circleci/project/build/CMakeFiles 0
make[1]: Leaving directory '/home/circleci/project/build'
+ git checkout ../flatpak/org.opencpn.OpenCPN.Plugin.logbook.yaml
Updated 1 path from the index
+ python3 -m pip install -q --user --upgrade pip
  WARNING: The scripts pip, pip3 and pip3.8 are installed in '/home/circleci/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: You are using pip version 20.1.1; however, version 21.1.3 is available.
You should consider upgrading via the '/opt/circleci/.pyenv/versions/3.8.5/bin/python3 -m pip install --upgrade pip' command.
+ python3 -m pip install -q --user cloudsmith-cli cryptography
  WARNING: The script chardetect is installed in '/home/circleci/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pysemver is installed in '/home/circleci/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script cloudsmith is installed in '/home/circleci/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
+ echo 'export PATH=$PATH:$HOME/.local/bin'

```
CircleCI received exit code 0


Skipping Cache
```
Skipping cache generation, cache already exists for key: fp-x86-18-v1-fvN0MELRBA0Z551xcGy3oxP3wm8DcO_+0KrjhnDM6oc=
Found one created at 2021-07-10 12:19:45 +0000 UTC

```
Upload.sh does not seem to be working because

```
Using upload repo: o p e n c p n / l o g b o o k k o n n i - a l p h a
+ cloudsmith push raw --no-wait-for-sync --name Logbook-1.4-flatpak-20.08-metadata --version 1.4.15.2-+941.f7f99a8 --summary 'Plugin metadata for automatic installation' opencpn/logbookkonni-alpha Logbook-1.4-flatpak-20.08.xml
Usage: cloudsmith push raw [OPTIONS] OWNER/REPO
                           PACKAGE_FILE
Try 'cloudsmith push raw -h' for help.

Error: Invalid value for 'PACKAGE_FILE': File 'Logbook-1.4-flatpak-20.08.xml' does not exist.

Exited with code exit status 2

CircleCI received exit code 2

```

**Comment by rgleason** [comment]
https://github.com/rgleason/LogbookKonni_pi
https://github.com/rgleason/LogbookKonni_pi/runs/3165125756

https://app.circleci.com/pipelines/github/rgleason/LogbookKonni_pi/87/workflows/efe27b92-65c8-4fea-8c16-47b6f80c12bf/jobs/984

https://app.circleci.com/pipelines/github/rgleason/LogbookKonni_pi/87/workflows/efe27b92-65c8-4fea-8c16-47b6f80c12bf/jobs/981

https://app.circleci.com/pipelines/github/rgleason/LogbookKonni_pi/87/workflows/efe27b92-65c8-4fea-8c16-47b6f80c12bf/jobs/974

**Comment by rgleason** [comment]
Have moved useless to data, may simply delete
