### ISSUE TITLE
Simple PR turned into a mess

### ISSUE THREAD

**Issue by rgleason** [rgleason/LogbookKonni_pi#49]
@leamas

Alec, I merged your PR for  Fix multiline description  https://github.com/rgleason/LogbookKonni_pi/commit/a850f3a038734757188f0d0c2843448877742fd1

Then this morning I tried to push this to Del at bable and must have gotten the direction reversed, so that my repository got screwed up.  Is there an easy way to undo this commit?  I hope so.

**Comment by leamas** [comment]
if you havn't pushed anything `git reset --hard` does it. Otherwise, `git revert` You need to google the details

**Comment by leamas** [comment]
OTOH, was that necessary? Remember, LogBook is *very* special when it uses the description in the C code. I have so far not seen any other plugin  doing this. And in those cases, everything works fine, just you define the description in. For shipdriver, that is (at the moment) in CMakeLists.txt

**Comment by rgleason** [comment]
It was a stupid mistake. Very sorry.
I have my local repository which is at  1.4.22.0 fix summary 
just like this  https://github.com/rgleason/LogbookKonni_pi/commit/6864882e5d1982775b5d684570830e91d42e78d1

Could I push that again?

**Comment by rgleason** [comment]
Or I could use Git Desktop and revert it.

**Comment by rgleason** [comment]
From my local repository master branch which is at "1.4.22.0 fix summary" 
similar to https://github.com/rgleason/LogbookKonni_pi/commit/6864882e5d1982775b5d684570830e91d42e78d1

What should I do?

**Comment by rgleason** [comment]
When I push it will just respond that my remote is ahead and to update local, so

git remote update origin
git rebase origin/main  
  Since there are no other commits it will just fast forward. could use git pull origin master.
Now local = remote origin, next reset the head to where we want to be.  "Fix multiline description https://github.com/rgleason/LogbookKonni_pi/commit/a850f3a038734757188f0d0c2843448877742fd1

git checkout a850f3a0387
git add ...
git commit -am "revert to fix multiline description"

**Comment by rgleason** [comment]
Closing, solved.
