### ISSUE TITLE
for the last versions of logbook the tar.gz archives are not built for flatpak

### ISSUE THREAD

**Issue by filochard** [rgleason/LogbookKonni_pi#52]
Hi Rick
I am testing the last updated version of OpenCPN  (5.6.0) inside an updated Flatpak (20.08)
I can't install logbookkonni (strangely the tar.gz for flatpak only contains a metadata.xml instead  of  4Mbytes of lib and data like the tar.gz for ubuntu, darwin, raspbian etc !?)
this true for
version 1.4.23
version 1.4.22
version 1.4.21

I had to download version 1.4.19 from cloudsmith.io which is correctly built and works perfectly (allowing to easily install the Layouts.zip  and to create the *.txt files in the right place)

**Comment by rgleason** [comment]
Thanks for advising. I need to update logbook anyway and will do so.

**Comment by filochard** [comment]
Hi Rick
You may close this issue now : 
version 1.4.26 is built for flatpak and is OK

**Comment by rgleason** [comment]
Thanks

**Comment by rgleason** [comment]
@filochard 

Can you volunteer to be a Plugin Tester for us?  We need more testers particularly for Flatpak versions.
Please see https://github.com/OpenCPN/plugins/issues/660
We need which OS version exactly, your name, your Cruiser Forum name, github name.
Thanks.
Rick

**Comment by filochard** [comment]
Hi Rick
I did it 
https://github.com/OpenCPN/plugins/issues/660#issuecomment-1108649763

**Comment by rgleason** [comment]
Thanks filochard
