### ISSUE TITLE
logbookkonni creates segfault when it's built upon wxgtk3.1.5 in linux

### ISSUE THREAD

**Issue by filochard** [rgleason/LogbookKonni_pi#60]
Hi Rick
As I said before in
https://github.com/rgleason/LogbookKonni_pi/issues/54
look at my comment
https://github.com/rgleason/LogbookKonni_pi/issues/54#issuecomment-1113984185

It is still valid...
I rebuilt all my rpms of OpenCPN 5.6.2 and its updated plugins  upon wxgtk3.0 
and tested them
When I use these rpms built upon wxgtk3.0 everything is OK

I rebuilt all these packages upon wxgtk3.15
I got a little problem to build Climatology which needs a little patch to be built : 
https://github.com/rgleason/climatology_pi/issues/35
With a fresh installation, everything is OK except logbookkonni : 
when I  launch it from is icon in the icon tray I get immediately a segfault

**Comment by rgleason** [comment]
With a fresh installation, everything is OK except logbookkonni :
--Thats great.

when I launch Logbook from its icon in the icon tray I get immediately a segfault

I think I've got to setup a virtual machine and try to get a flatpak setup, but I am a little short of that time right now.

Can you give use the segfault output?

**Comment by filochard** [comment]
Hi Rick
I tested this on a classical installation (rpms on a linux64bits system)
These rpms are not yet published (I wanted to test them a lot before providing them)

for the segfault with wxgtk3.1 unfortunately I only have this message in the console : 
segfault core dumped

I'm gonna investigate with gdb and debug packages but this will take some time (need to install a lot of debug packages : not only for OpenCPN and LogbookKonni  but also for wxgtk opengl tinyxml gettext and lots of others)

Nevertheless Everything is OK with wxgtk3.0 so for the moment I stand using this

NB take a look at the issue I opened for Climatology : there's one a little addition to add to the source so that it can be built upon wxgtk3.1.5 in linux if you don't you won't be able to build it
https://github.com/rgleason/climatology_pi/issues/35

**Comment by rgleason** [comment]
filochard,  we are doing a rental changeover tomorrow, but I think I can get to climatology.
How about the opencpn .log file that might have a clue.

**Comment by filochard** [comment]
we may close this issue since logbookkonni can now be built upon wxgtk3.2.0 and doesn't crash anymore
