### ISSUE TITLE
Bug: Memory leak

### ISSUE THREAD

**Issue by Kitiara** [rgleason/LogbookKonni_pi#63]
I don't get why do you create `Options` twice ?

1. I mean `create_pi` calls for ctor of `logbookkonni_pi` and then `Options` created.
https://github.com/rgleason/LogbookKonni_pi/blob/1ee7951810a153b240b9f4ec2f35b38bef914bc3/src/logbook_pi.cpp#L74
2. `Init` also creates `Options`.
https://github.com/rgleason/LogbookKonni_pi/blob/1ee7951810a153b240b9f4ec2f35b38bef914bc3/src/logbook_pi.cpp#L98

There we have a memory leak.

**Comment by sebastien-rosset** [comment]
This should be fixed by #68

**Comment by sebastien-rosset** [comment]
I think this issue can be closed.

**Comment by rgleason** [comment]
Thanks
