### ISSUE TITLE
the code should now be linked to https://github.com/OpenCPN/opencpn-libs instead of https://github.com/leamas/opencpn-libs

### ISSUE THREAD

**Issue by filochard** [rgleason/LogbookKonni_pi#64]
Hi Rick
Since Alec switched the opencpn-libs source to https://github.com/OpenCPN/opencpn-libs this URL may be used 

NB https://github.com/leamas/opencpn-libs is no more updated since october 23rd

**Comment by rgleason** [comment]
The current build should have a current opencpn-libs as Alec has made it all automatic for updates. Thanks.
Please close.

**Comment by filochard** [comment]
Hi Rick
Nice correction
